[_schema-version]
version = "0.2"

[project]
id = "gi-service"
name = "GI Service"
version = "1.0.0"

[[project.licenses]]
type = "Apache-2.0"

[build]
builder = "paketobuildpacks/builder-jammy-base"
exclude = [
    ".git",
    ".github",
    ".venv",
    "test",
    "tests",
    "__pycache__",
    "*.pyc"
]

[[build.env]]
name = "BP_CPYTHON_VERSION"
value = "3.12"

[[build.env]]
name = "BP_KEEP_FILES"
value = "static/*"
